export const SET_USER = 'SET_USER';
export const SET_JWT_TOKEN = 'SET_JWT_TOKEN';
export const ADD_TOAST_NOTIFICATION = 'ADD_TOAST_NOTIFICATION';
export const REMOVE_TOAST_NOTIFICATION = 'REMOVE_TOAST_NOTIFICATION';